"""add_user_table

Revision ID: e824a36d3801
Revises: 
Create Date: 2025-11-21 14:38:52.562855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql import sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e824a36d3801'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('username', sqltypes.AutoString(length=12), nullable=True),
    sa.Column('email', sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqltypes.AutoString(length=30), nullable=False),
    sa.Column('middle_name', sqltypes.AutoString(length=30), nullable=True),
    sa.Column('last_name', sqltypes.AutoString(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('security_question', sa.Enum('MOTHERS_MAIDEN_NAME', 'FIRST_PET_NAME', 'FAVORITE_TEACHER', 'BIRTH_CITY', 'FAVORITE_BOOK', name='securityquestionsschema'), nullable=False),
    sa.Column('security_answer', sqltypes.AutoString(length=30), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING', name='accountstatusschema'), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'ACCOUNT_EXECUTIVE', 'BRANCH_MANAGER', 'ADMIN', 'SUPER_ADMIN', 'TELLER', name='rolechoicesschema'), nullable=False),
    sa.Column('hashed_password', sqltypes.AutoString(length=256), nullable=False),
    sa.Column('failed_login_attempts', sa.SMALLINT(), nullable=False),
    sa.Column('last_failed_login', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('otp', sqltypes.AutoString(length=6), nullable=False),
    sa.Column('otp_expiry_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.execute('DROP TYPE rolechoicesschema')
    op.execute('DROP TYPE accountstatusschema')
    op.execute('DROP TYPE securityquestionsschema')
    # ### end Alembic commands ###
